# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: false
sudo: required
cache: packages
Remotes: gregce/ipify, 
   jimhester/covr
after_success:  
  - Rscript -e 'covr::coveralls()'
